sudo: required

language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "12"

script:
  - echo "npm test temporarily disabled"

install:
  - npm install
  - bash .travis/build.sh || true
  - ls build || true

deploy:
  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: dev-dmm-info.knstats.com
    skip_cleanup: true
    local-dir: build-ropsten
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: mumbai-dmm-info.knstats.com
    skip_cleanup: true
    local-dir: build-mumbai
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: staging-dmm-info.knstats.com
    skip_cleanup: true
    local-dir: build-staging
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^staging$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: staging-matic-dmm-info.knstats.com
    skip_cleanup: true
    local-dir: build-matic-staging
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^staging$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: staging-bsc-dmm-info.knstats.com
    skip_cleanup: true
    local-dir: build-bsc-staging
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^staging$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: staging-fantom-dmm-info.knstats.com
    skip_cleanup: true
    local-dir: build-fantom-staging
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^staging$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: analytics.kyberswap.com
    skip_cleanup: true
    local-dir: build-production
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^staging$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: polygon-analytics.kyberswap.com
    skip_cleanup: true
    local-dir: build-matic
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^staging$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: bsc-analytics.kyberswap.com
    skip_cleanup: true
    local-dir: build-bsc
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^staging$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: avax-analytics.kyberswap.com
    skip_cleanup: true
    local-dir: build-avax
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^staging$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: fantom-analytics.kyberswap.com
    skip_cleanup: true
    local-dir: build-fantom
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^staging$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: info.dmm.exchange
    skip_cleanup: true
    local-dir: build-production
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: info.dmm.exchange
    skip_cleanup: true
    local-dir: build-production-index
    cache_control: "public, max-age=30"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: polygon-info.dmm.exchange
    skip_cleanup: true
    local-dir: build-matic
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: polygon-info.dmm.exchange
    skip_cleanup: true
    local-dir: build-matic-index
    cache_control: "public, max-age=30"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: bsc-info.dmm.exchange
    skip_cleanup: true
    local-dir: build-bsc
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: bsc-info.dmm.exchange
    skip_cleanup: true
    local-dir: build-bsc-index
    cache_control: "public, max-age=30"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: avax-info.dmm.exchange
    skip_cleanup: true
    local-dir: build-avax
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: avax-info.dmm.exchange
    skip_cleanup: true
    local-dir: build-avax-index
    cache_control: "public, max-age=30"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$


  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: fantom-info.dmm.exchange
    skip_cleanup: true
    local-dir: build-fantom
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: fantom-info.dmm.exchange
    skip_cleanup: true
    local-dir: build-fantom-index
    cache_control: "public, max-age=30"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$
